import type { JobState } from "@/lib/api/types";

import completed from "./job-completed.json";
import failed from "./job-failed.json";
import running from "./job-running.json";

// Generated by apps/api/scripts/export_web_fixtures.py from the real backend models.
export const jobCompleted = completed as unknown as JobState;
export const jobRunning = running as unknown as JobState;
export const jobFailed = failed as unknown as JobState;
export const rawFixtures = { completed, running, failed };
