import type { DatasetProfile, JobState } from "@/lib/api/types";

import completed from "./job-completed.json";
import failed from "./job-failed.json";
import running from "./job-running.json";
import small from "./profile-small.json";

// Generated by apps/api/scripts/export_web_fixtures.py from the real backend:
// the e-commerce sample run through the findings battery and mock analyst.
export const jobCompleted = completed as unknown as JobState;
export const jobRunning = running as unknown as JobState;
export const jobFailed = failed as unknown as JobState;
// The 40-row sample's profile, with numbers small enough to check by hand.
export const profileSmall = small as unknown as DatasetProfile;
export const rawFixtures = { completed, running, failed };
